# Generated by Django 5.0.2 on 2024-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(verbose_name='Цена за покупку'),
        ),
    ]
